engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.php"
exclude_paths:
  - docs/
  - tests/
  - vendor/
